/*
 * $Id: HglResources.h,v 1.2 2000/05/16 16:05:27 fnevgeny Exp $
 *
 * Copyright (c) 1993 HAL Computer Systems International, Ltd.
 * 
 *          HAL COMPUTER SYSTEMS INTERNATIONAL, LTD.
 *                  1315 Dell Avenue
 *                  Campbell, CA  95008
 *
 * Author: Greg Hilton
 * Contributors: Tom Lang, Frank Bieser, and others
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * http://www.gnu.org/copyleft/gpl.html
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#ifndef _HglFallbackResources
#define _HglFallbackResources

#include <X11/Intrinsic.h>

static String HglFallbackResources[] = {
#if 0
"*iconDA.borderColor:	Blue",
"*XmFrame.borderColor:	green",
"*XmForm.borderColor:	red",
"*XmBulletinBoard.borderColor:	yellow",
"*XmPushButton.borderColor:	cyan",
"*XmPushButtonGadget.borderColor:	cyan",
"*XmRowColumn.borderColor:	green",
"*XmToggleButton.borderColor:	blue",
"*background:	LightGray",
"*foreground:	Black",
"*borderColor:	SteelBlue",
"*topShadowColor:	White",
"*bottomShadowColor:	Black",
"*highlightColor:	Red",
"*XmText.background:	LightSteelBlue",
"*XmText.foreground:	Black",
"*XmTextField.background:	LightSteelBlue",
"*XmTextField.foreground:	Black",
"*XmList.background:	LightYellow2",
"*XmList.foreground:	Black",
"*XmToggleButton.selectColor:	Magenta",
"*XmToggleButtonGadget.selectColor:	Magenta",
"*XmScrolledText*background:	LightSteelBlue",
"*insensitiveBackground:	LightGray",
"*insensitiveForeground:	Black",
"*optionalBackground:	LightSkyBlue1",
"*optionalForeground:	Black",
"*invalidBackground:	Red",
"*invalidForeground:	Black",
"*labelTextSpacing:	5",
"*allowShellResize:	True",
"*tearOffModel:	Tear_Off_Disabled",
"*multiClickTime:	300",
"*validDropIcon.pixmap:	thumb_up.xbm",
"*validDropIcon.mask:	thumb_up.mask",
"*invalidDropIcon.pixmap:	thumb_down.xbm",
"*invalidDropIcon.mask:	thumb_down.mask",
"*noDropIcon.pixmap:	thumb_down.xbm",
"*noDropIcon.mask:	thumb_down.mask",
"*HighlightThickness:	1",
"*HighlightColor:	red",
"*HighlightOnEnter:	true",
"*XmLabel.highlightOnEnter:	false",
"*XmLabel.highlightThickness:	0",
"*XmLabelGadget.highlightOnEnter:	false",
"*XmLabelGadget.highlightThickness:	0",
"*XmList.listSpacing:	2",
"*XmList.listMarginHeight:	2",
"*XmList.listMarginWidth:	10",
"*optionMenu*fontList:	-*-helvetica-bold-r-*-*-12-*-*-*-*-*-iso8859-1",
"*buttonFontList:	-*-helvetica-bold-r-*-*-12-*-*-*-*-*-iso8859-1",
"*labelFontList:	-*-helvetica-bold-r-*-*-12-*-*-*-*-*-iso8859-1",
"*textFontList:	-*-fixed-medium-r-*-*-14-*-*-*-*-*-iso8859-1",
"*XmFrame.marginWidth:	5",
"*XmFrame.marginHeight:	5",
"*XmFrame.shadowType:	Shadow_Etched_In",
"*XmSeparator.margin:	10",
"*XmSeparator.separatorType:	Shadow_Etched_Out",
"*XmSeparatorGadget.margin:	10",
"*XmSeparatorGadget.separatorType:	Shadow_Etched_Out",
"*XmLabel.marginWidth:	3",
"*XmLabel.marginHeight:	3",
"*XmLabelGadget.marginWidth:	3",
"*XmLabelGadget.marginHeight:	3",
"*XmDrawnButton.marginWidth:	2",
"*XmDrawnButton.marginHeight:	2",
"*XmPushButton.marginWidth:	3",
"*XmPushButton.marginHeight:	3",
"*XmPushButtonGadget.marginWidth:	3",
"*XmPushButtonGadget.marginHeight:	3",
"*XmToggleButton.marginWidth:	3",
"*XmToggleButton.marginHeight:	3",
"*XmToggleButtonGadget.marginWidth:	3",
"*XmToggleButtonGadget.marginHeight:	3",
"*XmPulldownMenu*XmPushButton.marginHeight:	3",
"*XmPulldownMenu*XmPushButton.marginWidth:	3",
"*XmPulldownMenu*XmPushButtonGadget.marginHeight:	3",
"*XmPulldownMenu*XmPushButtonGadget.marginWidth:	3",
"*msgDialog_popup.title:	Message",
"*msgDialog_popup.iconName:	Message",
"*rgbFilePath:	/usr/tools/X/0/lib/X11/rgb.txt",
"*mainWindow*appFrame.marginWidth:	10",
"*mainWindow*appFrame.marginHeight:	10",
"*mainWindow*appFrame.shadowType:	Shadow_Out",
"*mainWindow*msgWin*background:	Gray90",
"*mainWindow*msgWin*labelString:	_",
"*mainWindow*msgWin*fontList:	-*-helvetica-medium-r-*-*-12-*-*-*-*-*-iso8859-1",
"*mainWindow*fileButton.labelString:	File",
"*mainWindow*fileButton.mnemonic:	F",
"*mainWindow*fileExitButton.labelString:	Exit",
"*mainWindow*fileExitButton.accelerator:	Alt<Key>E",
"*mainWindow*fileExitButton.acceleratorText:	(Alt E)",
"*mainWindow*helpButton.labelString:	Help",
"*mainWindow*helpButton.mnemonic:	H",
"*mainWindow*helpButton.helpcard:	help-menu",
"*mainWindow*helpContextButton.labelString:	On Context",
"*mainWindow*helpContextButton.mnemonic:	C",
"*mainWindow*helpContextButton.accelerator:	Shift<Key>help",
"*mainWindow*helpContextButton.acceleratorText:	(Shift Help)",
"*mainWindow*helpWindowButton.labelString:	On Window",
"*mainWindow*helpWindowButton.mnemonic:	W",
"*mainWindow*helpKeysButton.labelString:	On Keys",
"*mainWindow*helpKeysButton.mnemonic:	K",
"*mainWindow*helpHelpButton.labelString:	On Help",
"*mainWindow*helpHelpButton.mnemonic:	H",
"*mainWindow*helpHelpButton.helpcard:	on-help",
"*mainWindow*helpIndexButton.labelString:	Index",
"*mainWindow*helpIndexButton.mnemonic:	I",
"*helpcardDbFiles:	Hal.hlp",
"*helpcard*helpText.rows:	10",
"*helpcard*helpText.columns:	65",
"*helpcard*helpText.wordWrap:	True",
"*helpcard.dialogTitle:	HaL Help Dialog",
"*helpcard.symbolPixmap:	hal.xbm",
"*helpcard.okLabelString:	OK",
"*helpcard.cancelLabelString:	OLIAS...",
"*helpcard.helpLabelString:	Help",
"*helpcard*helpHelpDialog.dialogTitle:	Help for HaL Help Dialog",
"*helpcard*helpHelpDialog.messageString:	When using the HaL Help Dialog:\\nPress the \"OK\" button if you want to close the Help Dialog.\\n Press the \"OLIAS...\" button to get more information via the OLIAS application.",
"*helpcard*helpErrorDialog.dialogTitle:	Error Using On-Line Help",
"*helpcard*helpErrorDialog.messageString: OLIAS not currently running.\\nYou must start OLIAS before using the \"OLIAS...\" button.\\nTo start OLIAS, type 'olias' at your nearest command-line.",
"*taskTitle.marginHeight:	0",
"*taskTitle.highlightThickness:	0",
"*largeIconViewPB.labelString:	View by Large Icon",
"*largeIconViewPB.mnemonic:	L",
"*smallIconViewPB.labelString:	View by Small Icon",
"*smallIconViewPB.mnemonic:	m",
"*fieldViewPB.labelString:	View by Detail",
"*fieldViewPB.mnemonic:	t",
"*byIconButton.labelString:	View by Large Icon",
"*byIconButton.mnemonic:	L",
"*byNameButton.labelString:	View by Small Icon",
"*byNameButton.mnemonic:	m",
"*selectButton.labelString:	Select All",
"*selectButton.mnemonic:	A",
"*deselectButton.labelString:	Deselect All",
"*deselectButton.mnemonic:	D",
"*filterButton.labelString:	Filter ...",
"*filterButton.mnemonic:	F",
"*sortButton.labelString:	Sort ...",
"*sortButton.mnemonic:	S",
"*findButton.labelString:	Find ...",
"*findButton.mnemonic:	i",
"*findLabel.labelString:	Name:",
"*findFirstButton.labelString:	Find First",
"*findNextButton.labelString:	Find Next",
"*findDoneButton.labelString:	Done",
"*findText.quickHelp:	Enter a name or pattern to be found",
"*findFirstButton.quickHelp:	Find the first item whose name contains the specified pattern",
"*findNextButton.quickHelp:	Find the next item whose name contains the specified pattern",
"*findDoneButton.quickHelp:	Close this window",
"*viewWin.?.background:	LightYellow2",
"*itemBoard*background:	LightYellow2",
"*totalLabel.labelString:	Total:",
"*dispLabel.labelString:	Displayed:",
"*selLabel.labelString:	Selected:",
"*dispLabel.leftOffset:	10",
"*selLabel.leftOffset:	10",
"*totalVal.foreground:	Blue",
"*dispVal.foreground:	Blue",
"*selVal.foreground:	Blue",
"*totalLabel.fontList:	9x15",
"*dispLabel.fontList:	9x15",
"*selLabel.fontList:	9x15",
"*totalVal.fontList:	9x15",
"*dispVal.fontList:	9x15",
"*selVal.fontList:	9x15",
"*findBlinkCount:	8",
"*findBlinkInterval:	50",
"*iconDA.selectedBackground:	Blue",
"*iconDA.selectedForeground:	Cyan",
"*iconDA.font:	-*-helvetica-bold-r-*-*-12-*-*-*-*-*-iso8859-1",
"*iconDA.horizSpacing:	5",
"*iconDA.vertSpacing:	5",
"*iconDA.labelOffset:	5",
"*iconDA.labelSpacing:	5",
"*iconDA.highlightThickness:	1",
"*iconDA.marginWidth:	5",
"*iconDA.marginHeight:	5",
"*iconDA.itemMarginWidth:	5",
"*iconDA.itemMarginHeight:	5",
"*fieldDA.selectedBackground:	Blue",
"*fieldDA.selectedForeground:	Cyan",
"*fieldDA.titleBackground:	LightGray",
"*fieldDA.font:	-*-helvetica-bold-r-*-*-12-*-*-*-*-*-iso8859-1",
"*fieldDA.vertSpacing:	2",
"*fieldDA.highlightThickness:	1",
"*fieldDA.separatorThickness:	1",
"*fieldDA.marginWidth:	5",
"*fieldDA.marginHeight:	5",
"*fieldDA.itemMarginWidth:	5",
"*fieldDA.itemMarginHeight:	5",
"*itemForm*background:	LightYellow2",
"*itemListSW.bottomOffset:	5",
"*itemText.bottomOffset:	5",
"*addButton.labelString:	Add",
"*remButton.labelString:	Remove",
"*repButton.labelString:	Replace",
"*clrButton.labelString:	Clear",
"*removeWin_popup.title:	Remove Entries",
"*removeWin_popup.iconName:	Remove Entries",
"*removeWin.messageString:	Remove the selected entries?",
"*removeWin.OK.labelString:	Yes",
"*removeWin.Cancel.labelString:	No",
"*clearWin_popup.title:	Clear List",
"*clearWin_popup.iconName:	Clear List",
"*clearWin.messageString:	Remove all entries?",
"*clearWin.OK.labelString:	Yes",
"*clearWin.Cancel.labelString:	No",
"*Command Output*columns:	80",
"*Command Output*rows:	10",
"*Command Output*defaultButtonShadowThickness:	1",
"*Command Output*outLabel.labelString:	Output:",
"*Command Output*errLabel.labelString:	Errors:",
"*Command Output*okPB.labelString:	Ok",
"*Command Output*cancelPB.labelString:	Cancel",
"*Sort*sortAZ.labelString:	Forward alphabetically",
"*Sort*sortZA.labelString:	Reverse alphabetically",
"*Sort*okPB.labelString:	Ok",
"*Sort*applyPB.labelString:	Apply",
"*Sort*cancelPB.labelString:	Cancel",
"*Sort*helpPB.labelString:	Help",
"*Filter*patLabel.labelString:	Pattern:",
"*Filter*displayTB.labelString:	Hide items failing filter",
"*Filter*selectTB.labelString:	Select items passing filter",
"*Filter*okPB.labelString:	Ok",
"*Filter*applyPB.labelString:	Apply",
"*Filter*cancelPB.labelString:	Cancel",
"*Filter*helpPB.labelString:	Help",
"*Find*patField.value:	.*",
"*Find*patLabel.labelString:	Pattern:",
"*Find*firstPB.labelString:	Find First",
"*Find*nextPB.labelString:	Find Next",
"*Find*donePB.labelString:	Done",
"*Find*helpPB.labelString:	Help",
"*termFrame.rightOffset:	1",
"*termArea.rows:	24",
"*termArea.columns:	80",
"*termArea.font:	9x15",
"*termArea.boldFont:	9x15bold",
"*termArea.scrollBar:	True",
"*termArea.pointerShape:	xterm",
"*termArea*loggingTB.labelString:	Log to File",
"*termArea*redrawPB.labelString:	Redraw Window",
"*termArea*sigStopPB.labelString:	Send STOP Signal",
"*termArea*sigContPB.labelString:	Send CONT Signal",
"*termArea*sigIntPB.labelString:	Send INT  Signal",
"*termArea*sigHupPB.labelString:	Send HUP  Signal",
"*termArea*sigTermPB.labelString:	Send TERM Signal",
"*termArea*sigKillPB.labelString:	Send KILL Signal",
"*termArea*scrollBarTB.labelString:	Show Scrollbar",
"*termArea*reverseVideoTB.labelString:	Reverse Video",
"*termArea*autoWrapTB.labelString:	Auto Wraparound",
"*termArea*appCursorTB.labelString:	Application Cursor Keys",
"*termArea*appKeypadTB.labelString:	Application Keypad",
"*termArea*scrollKeyTB.labelString:	Scroll to Bottom on Key Press",
"*termArea*scrollTtyOutputTB.labelString:	Scroll to Bottom on Tty Output",
"*termArea*c132TB.labelString:	Allow 80/132 Column Switching",
"*termArea*visualBellTB.labelString:	Visual Bell",
"*termArea*marginBellTB.labelString:	Margin Bell",
"*termArea*cutNewlineTB.labelString:	Include Newline in Triple Click",
"*termArea*cutToBeginningOfLineTB.labelString:	Include Beginning of Line in Triple Click",
"*termArea*signalInhibitTB.labelString:	Don't Allow Signals from Main Menu",
"*termArea*softResetPB.labelString:	Soft Reset",
"*termArea*fullResetPB.labelString:	Full Reset",
"*termArea*resetClearPB.labelString:	Reset and Clear Saved Lines",
"*termArea.translations:	#override\\n <Key> R4  :	TermC-set-scrollbar(toggle)\\n<Key> R5  :	TermC-hard-reset()\\n<Key> R6  :	TermC-set-reverse-video(toggle)\\n<Key> R7  :	TermC-scroll-back(100,page)\\n<Key> R8  :	TermC-scroll-back(1,line)       \\n<Key> R9  :	TermC-scroll-back(1,halfpage)\\n<Key> R13 :	TermC-scroll-forw(100,page)\\n<Key> R14 :	TermC-scroll-forw(1,line)\\n<Key> R15 :	TermC-scroll-forw(1,halfpage)",
"*gridBB.cellWidth:	32",
"*gridBB.cellHeight:	32",
"*modFormParamTitle.fontList:	-*-helvetica-bold-o-*-*-12-*-*-*-*-*-iso8859-1",
"*modFormColorTitle.fontList:	-*-helvetica-bold-o-*-*-12-*-*-*-*-*-iso8859-1",
"*modFormParamTitle.labelString:	Parameters",
"*modFormColorTitle.labelString:	Colors",
"*modFormColorRC.numColumns:	2",
"*formatModLabel.labelString:	Numeric format:",
"*formatModIntTB.labelString:	Integer",
"*formatModHexTB.labelString:	Hexadecimal",
"*formatModFloatTB.labelString:	Floating point",
"*formatModPrecisLabel.labelString:	decimal points",
"*formatModPrecisTF.columns:	3",
"*formatModPrecisTF.leftOffset:	5",
"*formatModRadioBox.packing:	Pack_Tight",
"*formatModFrame.shadowType:	Shadow_In",
"*formatModFrame*background:	Thistle",
"*formatModFrame.marginWidth:	0",
"*formatModFrame.marginHeight:	0",
"*shadowModTypeLabel.labelString:	Shadow type:",
"*shadowModInTB.labelString:	In",
"*shadowModOutTB.labelString:	Out",
"*shadowModEtchInTB.labelString:	Etched In",
"*shadowModEtchOutTB.labelString:	Etched Out",
"*shadowModThickLabel.labelString:	Thickness:",
"*shadowModPixelLabel.labelString:	pixels",
"*shadowModThickTF.columns:	3",
"*shadowModTypeRadioBox.packing:	Pack_Tight",
"*shadowModTypeFrame.shadowType:	Shadow_In",
"*shadowModTypeFrame*background:	Thistle",
"*shadowModTypeFrame.marginWidth:	0",
"*shadowModTypeFrame.marginHeight:	0",
"*orientModLabel.labelString:	Orientation:",
"*orientModVerticalTB.labelString:	Vertical",
"*orientModHorizontalTB.labelString:	Horizontal",
"*orientModRadioBox.packing:	Pack_Tight",
"*orientModFrame.shadowType:	Shadow_In",
"*orientModFrame*background:	Thistle",
"*orientModFrame.marginWidth:	0",
"*orientModFrame.marginHeight:	0",
"*backgroundMod*labelString:	Background:",
"*topShadowColorMod*labelString:	Top shadow:",
"*bottomShadowColorMod*labelString:	Bottom shadow:",
"*axisColorMod*labelString:	Axis:",
"*gridColorMod*labelString:	Grid:",
"*labelColorMod*labelString:	Label:",
"*lineColorMod*labelString:	Line:",
"*markColorMod*labelString:	Mark:",
"*tickColorMod*labelString:	Tick:",
"*valueColorMod*labelString:	Value:",
"*colorModDA.borderWidth:	1",
"*colorModDA.borderColor:	Black",
"*colorModLabel.rightOffset:	5",
"*colorModDA.rightOffset:	5",
"*counterMod*countLabel.labelString:	Digit count:",
"*counterMod*heightLabel.labelString:	Preferred digit height:",
"*counterMod*pixelLabel.labelString:	pixels",
"*counterMod*marginWidthLabel.labelString:	Margin width:",
"*counterMod*marginHeightLabel.labelString:	Margin height:",
"*counterMod*digitBackgroundMod*labelString:	Digit background:",
"*counterMod*digitForegroundMod*labelString:	Digit foreground:",
"*counterMod*shadowMod.topOffset:	5",
"*counterMod*countTF.columns:	3",
"*counterMod*heightTF.columns:	3",
"*counterMod*marginWidthTF.columns:	3",
"*counterMod*marginHeightTF.columns:	3",
"*counterMod*countTF.topOffset:	5",
"*counterMod*heightTF.topOffset:	5",
"*counterMod*marginWidthTF.topOffset:	5",
"*counterMod*marginHeightTF.topOffset:	5",
"*scaleMod*minLabel.labelString:	Minimum value:",
"*scaleMod*maxLabel.labelString:	Maximum value:",
"*scaleMod*barShadowMod*shadowModTypeLabel.labelString:	Bar shadow type:",
"*scaleMod*troughShadowMod*shadowModTypeLabel.labelString:	Trough shadow type:",
"*scaleMod*sizeLabel.labelString:	Preferred trough size:",
"*scaleMod*pixelLabel.labelString:	pixels",
"*scaleMod*barColorMod*labelString:	Bar:",
"*scaleMod*troughColorMod*labelString:	Trough:",
"*scaleMod*barTopShadowColorMod*labelString:	Bar top shadow:",
"*scaleMod*barBottomShadowColorMod*labelString:	Bar bottom shadow:",
"*scaleMod*troughTopShadowColorMod*labelString:	Trough top shadow:",
"*scaleMod*troughBottomShadowColorMod*labelString:	Trough bottom shadow:",
"*scaleMod*minTF.columns:	8",
"*scaleMod*maxTF.columns:	8",
"*scaleMod*formatMod.topOffset:	5",
"*scaleMod*barShadowMod.topOffset:	5",
"*scaleMod*troughShadowMod.topOffset:	5",
"*scaleMod*orientationMod.topOffset:	5",
"*scaleMod*sizeTF.columns:	3",
"*scaleMod*sizeTF.topOffset:	5",
"*meterMod*minLabel.labelString:	Minimum value:",
"*meterMod*maxLabel.labelString:	Maximum value:",
"*meterMod*majorTickSpacingLabel.labelString:	Primary tick mark spacing:",
"*meterMod*minorTickSpacingLabel.labelString:	Secondary tick mark spacing:",
"*meterMod*majorTickLengthLabel.labelString:	Primary tick mark length:",
"*meterMod*minorTickLengthLabel.labelString:	Secondary tick mark length:",
"*meterMod*faceColorMod*labelString:	Face:",
"*meterMod*indicatorColorMod*labelString:	Indicator:",
"*meterMod*minTF.columns:	8",
"*meterMod*maxTF.columns:	8",
"*meterMod*majorTickSpacingTF.columns:	8",
"*meterMod*minorTickSpacingTF.columns:	8",
"*meterMod*majorTickLengthTF.columns:	8",
"*meterMod*minorTickLengthTF.columns:	8",
"*meterMod*majorTickSpacingTF.topOffset:	5",
"*meterMod*majorTickLengthTF.topOffset:	5",
"*meterMod*formatMod.topOffset:	5",
"*meterMod*shadowMod.topOffset:	5",
"*stripMod*majorTickLengthLabel.labelString:	Length of primary tick marks:",
"*stripMod*minorTickLengthLabel.labelString:	Length of secondary tick marks:",
"*stripMod*marginWidthLabel.labelString:	Margin width:",
"*stripMod*marginHeightLabel.labelString:	Margin height:",
"*stripMod*xAxisTitle.labelString:	X Axis",
"*stripMod*majorXTickSpacingLabel.labelString:	Primary tick mark spacing:",
"*stripMod*minorXTickSpacingLabel.labelString:	Secondary tick mark spacing:",
"*stripMod*majorXGridTB.labelString:	Show primary grid",
"*stripMod*minorXGridTB.labelString:	Show secondary grid",
"*stripMod*visibleValueCountLabel.labelString:	Visible value count:",
"*stripMod*maximumValueCountLabel.labelString:	Maximum value count:",
"*stripMod*yAxisTitle.labelString:	Y Axis",
"*stripMod*minLabel.labelString:	Minimum value:",
"*stripMod*maxLabel.labelString:	Maximum value:",
"*stripMod*majorYTickSpacingLabel.labelString:	Primary tick mark spacing:",
"*stripMod*minorYTickSpacingLabel.labelString:	Secondary tick mark spacing:",
"*stripMod*majorYGridTB.labelString:	Show primary grid",
"*stripMod*minorYGridTB.labelString:	Show secondary grid",
"*stripMod*chartColorMod*labelString:	Chart:",
"*stripMod*majorTickLengthTF.columns:	3",
"*stripMod*minorTickLengthTF.columns:	3",
"*stripMod*marginWidthTF.columns:	3",
"*stripMod*marginHeightTF.columns:	3",
"*stripMod*majorXTickSpacingTF.columns:	8",
"*stripMod*minorXTickSpacingTF.columns:	8",
"*stripMod*visibleValueCountTF.columns:	8",
"*stripMod*maximumValueCountTF.columns:	8",
"*stripMod*minTF.columns:	8",
"*stripMod*maxTF.columns:	8",
"*stripMod*majorYTickSpacingTF.columns:	8",
"*stripMod*minorYTickSpacingTF.columns:	8",
"*stripMod*majorTickLengthTF.topOffset:	5",
"*stripMod*marginWidthTF.topOffset:	5",
"*stripMod*xAxisFrame.leftOffset:	5",
"*stripMod*xAxisFrame.rightOffset:	5",
"*stripMod*xAxisFrame.topOffset:	5",
"*stripMod*minorXTickSpacingTF.topOffset:	5",
"*stripMod*visibleValueCountTF.topOffset:	5",
"*stripMod*maximumValueCountLabel.leftOffset:	5",
"*stripMod*maximumValueCountTF.leftOffset:	5",
"*stripMod*yAxisFrame.leftOffset:	5",
"*stripMod*yAxisFrame.rightOffset:	5",
"*stripMod*yAxisFrame.topOffset:	5",
"*stripMod*majorYTickSpacingTF.topOffset:	5",
"*stripMod*minorYTickSpacingTF.topOffset:	5",
"*stripMod*formatMod.topOffset:	5",
"*histMod*barShadowMod*shadowModTypeLabel.labelString:	Bar shadow type:",
"*histMod*majorTickLengthLabel.labelString:	Length of primary tick marks:",
"*histMod*minorTickLengthLabel.labelString:	Length of secondary tick marks:",
"*histMod*marginWidthLabel.labelString:	Margin width:",
"*histMod*marginHeightLabel.labelString:	Margin height:",
"*histMod*maximumValueCountLabel.labelString:	Maximum value count:",
"*histMod*valueAxisTitle.labelString:	Value Axis",
"*histMod*bucketWidthLabel.labelString:	Bucket width:",
"*histMod*visibleBucketCountLabel.labelString:	Visible bucket count:",
"*histMod*majorValueTickSpacingLabel.labelString:	Primary tick mark spacing:",
"*histMod*minorValueTickSpacingLabel.labelString:	Secondary tick mark spacing:",
"*histMod*countAxisTitle.labelString:	Count Axis",
"*histMod*countShowZeroTB.labelString:	Always show zero",
"*histMod*countCompressTB.labelString:	Show count range only",
"*histMod*majorCountTickSpacingLabel.labelString:	Primary tick mark spacing:",
"*histMod*minorCountTickSpacingLabel.labelString:	Secondary tick mark spacing:",
"*histMod*majorGridTB.labelString:	Show primary grid",
"*histMod*minorGridTB.labelString:	Show secondary grid",
"*histMod*chartColorMod*labelString:	Chart:",
"*histMod*barColorMod*labelString:	Bar:",
"*histMod*barBorderColorMod*labelString:	Bar border:",
"*histMod*barTopShadowColorMod*labelString:	Bar top shadow:",
"*histMod*barBottomShadowColorMod*labelString:	Bar bottom shadow:",
"*histMod*majorTickLengthTF.columns:	3",
"*histMod*minorTickLengthTF.columns:	3",
"*histMod*marginWidthTF.columns:	3",
"*histMod*marginHeightTF.columns:	3",
"*histMod*maximumValueCountTF.columns:	8",
"*histMod*bucketWidthTF.columns:	8",
"*histMod*visibleBucketCountTF.columns:	8",
"*histMod*majorValueTickSpacingTF.columns:	8",
"*histMod*minorValueTickSpacingTF.columns:	8",
"*histMod*majorCountTickSpacingTF.columns:	8",
"*histMod*minorCountTickSpacingTF.columns:	8",
"*histMod*countCompressFrame.shadowType:	Shadow_In",
"*histMod*countCompressFrame*background:	Thistle",
"*histMod*countCompressFrame.marginWidth:	0",
"*histMod*countCompressFrame.marginHeight:	0",
"*histMod*countCompressRadioBox.packing:	Pack_Tight",
"*histMod*barShadowMod.topOffset:	5",
"*histMod*majorTickLengthTF.topOffset:	5",
"*histMod*marginWidthTF.topOffset:	5",
"*histMod*orientationMod.topOffset:	5",
"*histMod*maximumvalueCountLabel.leftOffset:	5",
"*histMod*maximumvalueCountTF.leftOffset:	5",
"*histMod*valueAxisFrame.leftOffset:	5",
"*histMod*valueAxisFrame.rightOffset:	5",
"*histMod*valueAxisFrame.topOffset:	5",
"*histMod*bucketWidthTF.topOffset:	5",
"*histMod*visibleBucketCountTF.topOffset:	5",
"*histMod*majorValueTickSpacingTF.topOffset:	5",
"*histMod*countAxisFrame.leftOffset:	5",
"*histMod*countAxisFrame.rightOffset:	5",
"*histMod*countAxisFrame.topOffset:	5",
"*histMod*countCompressFrame.topOffset:	5",
"*histMod*majorCountTickSpacingTF.topOffset:	5",
"*histMod*minorCountTickSpacingTF.topOffset:	5",
"*Comment PostCard*XmText.translations:	#override Ctrl<Key>D:	activate() \\nCtrl<Key>U:	kill_to_start_of_line()\\nCtrl<Key>W:	delete-previous-work()\\n<Key>osfDelete:	delete-previous-character()",
"*Comment PostCard*msg-text.rows:	15",
"*Comment PostCard*msg-text.columns:	60",
"*Comment PostCard*postcard.labelString:	Post Card",
"*Comment PostCard*title.labelString:	Quick Comment Sender",
"*Comment PostCard*actions*leftAttachment:	attach_position",
"*Comment PostCard*actions*rightAttachment:	attach_position",
"*Comment PostCard*abstractLabel.labelString:	Abstract:",
"*Comment PostCard*abstractText.quickHelp:	Enter a short desription of the condition. This is a required field",
"*Comment PostCard*itemText.quickHelp:	Enter additional mail addresses to whom this Postcard will be sent.",
"*Comment PostCard*msg-text.quickHelp:	Enter any necessary information pertinent to the condition. This is not required.",
"*Comment PostCard*textTitle.labelString:	Description/Comments:",
"*Comment PostCard*toTitle.labelString:	To:",
"*Comment PostCard*to-list.visibleItemCount:	6",
"*Comment PostCard*subjTitle.labelString:	Subject:  ",
"*Comment PostCard*catLabel.labelString:	Categories",
"*Comment PostCard*sevLabel.labelString:	Severity",
"*Comment PostCard*bugTB.labelString:	Bug",
"*Comment PostCard*bugTB.quickHelp:	The change requested in this message represents an error in the product.",
"*Comment PostCard*perfTB.labelString:	Performance",
"*Comment PostCard*perfTB.quickHelp:	The change requested in this message represents an enhancement to the product.",
"*Comment PostCard*commentTB.labelString:	Enhancement",
"*Comment PostCard*commentTB.quickHelp:	The change requested in this message represents an enhancement to the product.",
"*Comment PostCard*crucialTB.labelString:	Crucial",
"*Comment PostCard*crucialTB.quickHelp:	The change requested in this message is of crucial importance.",
"*Comment PostCard*majorTB.labelString:	Major",
"*Comment PostCard*majorTB.quickHelp:	The change requested in this message is of major importance.",
"*Comment PostCard*mediumTB.labelString:	Medium",
"*Comment PostCard*mediumTB.quickHelp:	The change requested in this message is of medium importance.",
"*Comment PostCard*minorTB.labelString:	Minor",
"*Comment PostCard*minorTB.quickHelp:	The change requested in this message is of minor importance.",
"*Comment PostCard*send-btn.labelString:	Send",
"*Comment PostCard*send-btn.quickHelp:	Use this button to Send the message to the recipients",
"*Comment PostCard*quit-btn.labelString:	Quit",
"*Comment PostCard*quit-btn.quickHelp:	Use this button to Close the Post Card.",
"*Comment PostCard*error.messageString:	You must provide at least one message recipient.",
"*Comment PostCard*error.cancelLabelString:	OK",
"*pieChartMod*sliceForm.?.topOffset:	5",
"*pieChartMod*sliceForm.?.bottomOffset:	5",
"*pieChartMod*paramForm.?.topOffset:	5",
"*pieChartMod*paramForm.?.bottomOffset:	5",
"*pieChartMod*sliceLineWidthVFLabel.labelString:	Line Width:",
"*pieChartMod*paramFrameLabel.labelString:	Pie Parameters",
"*pieChartMod*paramForm*titleLabel.labelString:	Title:",
"*pieChartMod*paramForm*thicknessLabel.labelString:	Thickness:",
"*pieChartMod*paramForm*valueLabel.labelString:	Total Value:",
"*pieChartMod*paramForm*declinationLabel.labelString:	Declination:",
"*pieChartMod*paramForm*lineWidthLabel.labelString:	Default Line Width:",
"*pieChartMod*paramForm*rotationLabel.labelString:	Rotation:",
"*pieChartMod*legendVisTB.labelString:	Legend",
"*pieChartMod*legendTextShadowTB.labelString:	Legend Text Shadow",
"*pieChartMod*titleTextShadowTB.labelString:	Title Text Shadow",
"*pieChartMod*labelTextShadowTB.labelString:	Label Text Shadow",
"*pieChartMod*labelFormatFrame.marginWidth:	0",
"*pieChartMod*labelFormatFrame.marginHeight:	0",
"*pieChartMod*labelFormatForm.marginWidth:	0",
"*pieChartMod*labelFormatForm.marginHeight:	0",
"*pieChartMod*sliceFrameLabel.labelString:	Slice Parameters",
"*pieChartMod*sliceListLabel.labelString:	Slices:",
"*pieChartMod*sliceLabelLabel.labelString:	Label:",
"*pieChartMod*sliceValueLabel.labelString:	Value:",
"*pieChartMod*sliceOffsetLabel.labelString:	Offset:",
"*pieChartMod*sliceTopColorMod.colorModLabel.labelString:	Top Color:",
"*pieChartMod*sliceInnerColorMod.colorModLabel.labelString:	Inner Color:",
"*pieChartMod*sliceOuterColorMod.colorModLabel.labelString:	Outer Color:",
"*pieChartMod*sliceLineWidthVF*sliceLineWidthLabel.labelString:	Line Width:",
"*pieChartMod*colorModLabel.rightOffset:	1",
"*pieChartMod*colorForm*topOffset:	2",
"*pieChartMod*colorForm*bottomOffset:	2",
"*pieChartMod*colorFrameLabel.labelString:	Pie Colors",
"*pieChartMod*backgroundColorMod*labelString:	Background Color:",
"*pieChartMod*lineColorMod*labelString:	Line Color:",
"*pieChartMod*legendTextColorMod*labelString:	Legend Text Color:",
"*pieChartMod*legendShadowColorMod*labelString:	Legend Shadow Color:",
"*pieChartMod*titleTextColorMod*labelString:	Title Text Color:",
"*pieChartMod*titleShadowColorMod*labelString:	Title Shadow Color:",
"*pieChartMod*labelTextColorMod*labelString:	Label Text Color:",
"*pieChartMod*labelShadowColorMod*labelString:	Label Shadow Color:",
"*pieChartMod*visLabel.labelString:	Visibilities:",
"*pieChartMod*legendValueTypeMod.label.labelString:	Legend Format:",
"*pieChartMod*labelValueTypeMod.label.labelString:	Label Format:",
"*pieChartMod*noneTB.labelString:	None",
"*pieChartMod*intTB.labelString:	Integer",
"*pieChartMod*percentTB.labelString:	Percent",
"*pieChartMod*floatTB.labelString:	Floating Point",
"*pieChartMod*hexTB.labelString:	Hexidecimal",
"*pieChartMod*precisionLabel.labelString:	Decimal Pts",
"*pieChartMod*precisionTF.columns:	3",
"*boolExpWin*lparPB.labelString:	(",
"*boolExpWin*rparPB.labelString:	)",
"*boolExpWin*andPB.labelString:	AND",
"*boolExpWin*orPB.labelString:	OR",
"*boolExpWin*notPB.labelString:	NOT",
"*boolExpWin*expWin.topOffset:	5",
"*boolExpWin*buttonRC.defaultButtonShadowThickness:	2",
"*boolExpWin*okPB.labelString:	Ok",
"*boolExpWin*applyPB.labelString:	Apply",
"*boolExpWin*clearPB.labelString:	Clear",
"*boolExpWin*cancelPB.labelString:	Cancel",
"*boolExpWin*helpPB.labelString:	Help",
"*boolExpWin*expDA*translations: <Key>(:	BoolExpWinC-insert-lparen()	\\n<Key>):	BoolExpWinC-insert-rparen()	\\n<Key>&:	BoolExpWinC-insert-and()\\n<Key>|:	BoolExpWinC-insert-or()\\n<Key>!:	BoolExpWinC-insert-not()\\n<Key>osfBackSpace:	BoolExpWinC-delete-left()\\n<Key>osfDelete:	BoolExpWinC-delete-right()\\n <Btn1Down>,<Btn1Up>:	BoolExpWinC-move-pointer()",
"*boolExpWin*expDA.trueLabel.labelString:	True",
"*boolExpWin*expDA.falseLabel.labelString:	False",
"*boolExpWin*expDA.lparLabel.labelString:	(",
"*boolExpWin*expDA.rparLabel.labelString:	)",
"*boolExpWin*expDA.andLabel.labelString:	and",
"*boolExpWin*expDA.orLabel.labelString:	or",
"*boolExpWin*expDA.notLabel.labelString:	!",
"*boolExpWin*expDA.marginWidth:	0",
"*boolExpWin*expDA.marginHeight:	0",
"*boolExpWin*expDA.cursor.labelString:	|",
"*boolExpWin*expDA.cursor.fontList:	-*-times-bold-r-normal-*-24-*-*-*-*-*-*-*",
"*boolExpWin*expDA.cursor.blinkRate:	2",
"*boolExpWin*expDA.cursor.foreground:	Red",
"*boolExpWin*expDA.andLabel.foreground:	Blue",
"*boolExpWin*expDA.orLabel.foreground:	Blue",
"*boolExpWin*expDA.notLabel.foreground:	Blue",
#endif
NULL
};

#endif
